### ISSUE TITLE
Why do we need to run chmod 755 before the cleaning.command

### ISSUE THREAD

**Issue by ArsalaBangash** [milindvishnoi/Download-Folder-Organizer#3]
The title is self explanatory

**Comment by milindvishnoi** [comment]
We need to change the read/write permissions as the script will change the file location.

**Comment by ArsalaBangash** [comment]
Let's make it clear in the documentation and link to a resource.

**Comment by milindvishnoi** [comment]
@ArsalaBangash Just made the required changes!
